[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firebase-admin>=7.1.0",
    "requests>=2.32.5",
    "sseclient>=0.0.27",
    "python-dotenv>=0.9.9",
    "pytz",
]
